const LOAD_PRODUCTS = 'LOAD_PRODUCTS';
const LOAD_ORDERS = 'LOAD_ORDERS';
const SET_AUTH = 'SET_AUTH';
const SET_COUNT = 'SET_COUNT';

export {
  LOAD_PRODUCTS,
  LOAD_ORDERS,
  SET_AUTH,
  SET_COUNT
};
